### ISSUE TITLE
Combo box does not work in dark mode

### ISSUE THREAD

**Issue by fhg-isi** [fraunhofer-isi/micat-vue#33]
A collegue could not use the micat front end because he had dark mode enabled (Firefox, Windows 10).

=> Disable support for dark mode (if possible?) or fix combo box. 

![image](https://github.com/fraunhofer-isi/micat-vue/assets/76424482/69c2f766-2fa3-4001-acca-bda3b91807bb)

@Tyrdall

**Comment by Tyrdall** [comment]
@fhg-isi A potential fix has been deployed. Please make sure to clear cache before testing.
Since I don't have access to Windows and hence had no option to test it, there might be a need for further improvements.

**Comment by fhg-isi** [comment]
@Tyrdall 
Issue is still present. 
![image](https://github.com/fraunhofer-isi/micat-vue/assets/76424482/79ad6987-0784-4cef-b5b0-ba6b8ce92335)

**Comment by Tyrdall** [comment]
@fhg-isi Somehow the latest code is not deployed. I can't tell why. Were there changes regarding the rollout?

**Comment by Tyrdall** [comment]
@fhg-isi Please check again.
